// Code generated by Kitex v0.4.2. DO NOT EDIT.

package echo

import (
	server "github.com/cloudwego/kitex/server"
	pbapi "learn-go/kitex-hello/kitex_gen/pbapi"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler pbapi.Echo, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(any(err))
	}
	if err := s.Init(); err != nil {
		panic(any(err))
	}
	return s
}
